[package]
name = "freebsd-zonecmd"
version = "0.1.0"
edition = "2024"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Rust bindings for FreeBSD's DIOCZONECMD ioctl"
categories = ["api-bindings", "os::freebsd-apis"]
keywords = ["FreeBSD", "ZBC", "ZAC", "SMR"]
rust-version = "1.85"
include = ["src/**/*", "bindgen/**/*", "examples/**/*", "LICENSE-*", "README.md"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-freebsd"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
gzoned = ["dep:mdconfig", "dep:tempfile"]

[dependencies]
cfg-if = "1.0"
libc = { version = "0.2.154", features = ["extra_traits"] }
mdconfig = { version = "0.2.0", optional = true }
nix = { version = ">=0.24.0,<0.32.0", default-features = false, features = ["ioctl"] }
tempfile = { version = "3.8", optional = true }

[dev-dependencies]
rstest = "0.19.0"

[[test]]
name = "integration"
required-features = ["gzoned"]
