#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(unused)]
#![allow(missing_docs)]
/* automatically generated by rust-bindgen 0.72.1 */

pub const DISK_ZONE_MODE_NONE: u32 = 0;
pub const DISK_ZONE_MODE_HOST_AWARE: u32 = 1;
pub const DISK_ZONE_MODE_DRIVE_MANAGED: u32 = 2;
pub const DISK_ZONE_MODE_HOST_MANAGED: u32 = 4;
pub const DISK_ZONE_DISK_URSWRZ: u32 = 1;
pub const DISK_ZONE_OPT_SEQ_SET: u32 = 2;
pub const DISK_ZONE_OPT_NONSEQ_SET: u32 = 4;
pub const DISK_ZONE_MAX_SEQ_SET: u32 = 8;
pub const DISK_ZONE_RZ_SUP: u32 = 16;
pub const DISK_ZONE_OPEN_SUP: u32 = 32;
pub const DISK_ZONE_CLOSE_SUP: u32 = 64;
pub const DISK_ZONE_FINISH_SUP: u32 = 128;
pub const DISK_ZONE_RWP_SUP: u32 = 256;
pub const DISK_ZONE_CMD_SUP_MASK: u32 = 496;
pub const DISK_ZONE_RWP_FLAG_NONE: u32 = 0;
pub const DISK_ZONE_RWP_FLAG_ALL: u32 = 1;
pub const DISK_ZONE_SAME_ALL_DIFFERENT: u32 = 0;
pub const DISK_ZONE_SAME_ALL_SAME: u32 = 1;
pub const DISK_ZONE_SAME_LAST_DIFFERENT: u32 = 2;
pub const DISK_ZONE_SAME_TYPES_DIFFERENT: u32 = 3;
pub const DISK_ZONE_TYPE_CONVENTIONAL: u32 = 1;
pub const DISK_ZONE_TYPE_SEQ_REQUIRED: u32 = 2;
pub const DISK_ZONE_TYPE_SEQ_PREFERRED: u32 = 3;
pub const DISK_ZONE_COND_NOT_WP: u32 = 0;
pub const DISK_ZONE_COND_EMPTY: u32 = 1;
pub const DISK_ZONE_COND_IMPLICIT_OPEN: u32 = 2;
pub const DISK_ZONE_COND_EXPLICIT_OPEN: u32 = 3;
pub const DISK_ZONE_COND_CLOSED: u32 = 4;
pub const DISK_ZONE_COND_READONLY: u32 = 13;
pub const DISK_ZONE_COND_FULL: u32 = 14;
pub const DISK_ZONE_COND_OFFLINE: u32 = 15;
pub const DISK_ZONE_FLAG_RESET: u32 = 1;
pub const DISK_ZONE_FLAG_NON_SEQ: u32 = 2;
pub const DISK_ZONE_REP_ALL: u32 = 0;
pub const DISK_ZONE_REP_EMPTY: u32 = 1;
pub const DISK_ZONE_REP_IMP_OPEN: u32 = 2;
pub const DISK_ZONE_REP_EXP_OPEN: u32 = 3;
pub const DISK_ZONE_REP_CLOSED: u32 = 4;
pub const DISK_ZONE_REP_FULL: u32 = 5;
pub const DISK_ZONE_REP_READONLY: u32 = 6;
pub const DISK_ZONE_REP_OFFLINE: u32 = 7;
pub const DISK_ZONE_REP_RWP: u32 = 16;
pub const DISK_ZONE_REP_NON_SEQ: u32 = 17;
pub const DISK_ZONE_REP_NON_WP: u32 = 63;
pub const DISK_ZONE_OPEN: u32 = 0;
pub const DISK_ZONE_CLOSE: u32 = 1;
pub const DISK_ZONE_FINISH: u32 = 2;
pub const DISK_ZONE_REPORT_ZONES: u32 = 3;
pub const DISK_ZONE_RWP: u32 = 4;
pub const DISK_ZONE_GET_PARAMS: u32 = 5;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct disk_zone_disk_params {
    pub zone_mode: u32,
    pub flags: u64,
    pub optimal_seq_zones: u64,
    pub optimal_nonseq_zones: u64,
    pub max_seq_zones: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of disk_zone_disk_params"][::std::mem::size_of::<disk_zone_disk_params>() - 36usize];
    ["Alignment of disk_zone_disk_params"]
        [::std::mem::align_of::<disk_zone_disk_params>() - 4usize];
    ["Offset of field: disk_zone_disk_params::zone_mode"]
        [::std::mem::offset_of!(disk_zone_disk_params, zone_mode) - 0usize];
    ["Offset of field: disk_zone_disk_params::flags"]
        [::std::mem::offset_of!(disk_zone_disk_params, flags) - 4usize];
    ["Offset of field: disk_zone_disk_params::optimal_seq_zones"]
        [::std::mem::offset_of!(disk_zone_disk_params, optimal_seq_zones) - 12usize];
    ["Offset of field: disk_zone_disk_params::optimal_nonseq_zones"]
        [::std::mem::offset_of!(disk_zone_disk_params, optimal_nonseq_zones) - 20usize];
    ["Offset of field: disk_zone_disk_params::max_seq_zones"]
        [::std::mem::offset_of!(disk_zone_disk_params, max_seq_zones) - 28usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct disk_zone_rwp {
    pub id: u64,
    pub flags: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of disk_zone_rwp"][::std::mem::size_of::<disk_zone_rwp>() - 12usize];
    ["Alignment of disk_zone_rwp"][::std::mem::align_of::<disk_zone_rwp>() - 4usize];
    ["Offset of field: disk_zone_rwp::id"][::std::mem::offset_of!(disk_zone_rwp, id) - 0usize];
    ["Offset of field: disk_zone_rwp::flags"]
        [::std::mem::offset_of!(disk_zone_rwp, flags) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct disk_zone_rep_header {
    pub same: u8,
    pub maximum_lba: u64,
    pub reserved: [u8; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of disk_zone_rep_header"][::std::mem::size_of::<disk_zone_rep_header>() - 76usize];
    ["Alignment of disk_zone_rep_header"][::std::mem::align_of::<disk_zone_rep_header>() - 4usize];
    ["Offset of field: disk_zone_rep_header::same"]
        [::std::mem::offset_of!(disk_zone_rep_header, same) - 0usize];
    ["Offset of field: disk_zone_rep_header::maximum_lba"]
        [::std::mem::offset_of!(disk_zone_rep_header, maximum_lba) - 4usize];
    ["Offset of field: disk_zone_rep_header::reserved"]
        [::std::mem::offset_of!(disk_zone_rep_header, reserved) - 12usize];
};
impl Default for disk_zone_rep_header {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct disk_zone_rep_entry {
    pub zone_type: u8,
    pub zone_condition: u8,
    pub zone_flags: u8,
    pub zone_length: u64,
    pub zone_start_lba: u64,
    pub write_pointer_lba: u64,
    pub reserved: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of disk_zone_rep_entry"][::std::mem::size_of::<disk_zone_rep_entry>() - 60usize];
    ["Alignment of disk_zone_rep_entry"][::std::mem::align_of::<disk_zone_rep_entry>() - 4usize];
    ["Offset of field: disk_zone_rep_entry::zone_type"]
        [::std::mem::offset_of!(disk_zone_rep_entry, zone_type) - 0usize];
    ["Offset of field: disk_zone_rep_entry::zone_condition"]
        [::std::mem::offset_of!(disk_zone_rep_entry, zone_condition) - 1usize];
    ["Offset of field: disk_zone_rep_entry::zone_flags"]
        [::std::mem::offset_of!(disk_zone_rep_entry, zone_flags) - 2usize];
    ["Offset of field: disk_zone_rep_entry::zone_length"]
        [::std::mem::offset_of!(disk_zone_rep_entry, zone_length) - 4usize];
    ["Offset of field: disk_zone_rep_entry::zone_start_lba"]
        [::std::mem::offset_of!(disk_zone_rep_entry, zone_start_lba) - 12usize];
    ["Offset of field: disk_zone_rep_entry::write_pointer_lba"]
        [::std::mem::offset_of!(disk_zone_rep_entry, write_pointer_lba) - 20usize];
    ["Offset of field: disk_zone_rep_entry::reserved"]
        [::std::mem::offset_of!(disk_zone_rep_entry, reserved) - 28usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct disk_zone_report {
    pub starting_id: u64,
    pub rep_options: u8,
    pub header: disk_zone_rep_header,
    pub entries_allocated: u32,
    pub entries_filled: u32,
    pub entries_available: u32,
    pub entries: *mut disk_zone_rep_entry,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of disk_zone_report"][::std::mem::size_of::<disk_zone_report>() - 104usize];
    ["Alignment of disk_zone_report"][::std::mem::align_of::<disk_zone_report>() - 4usize];
    ["Offset of field: disk_zone_report::starting_id"]
        [::std::mem::offset_of!(disk_zone_report, starting_id) - 0usize];
    ["Offset of field: disk_zone_report::rep_options"]
        [::std::mem::offset_of!(disk_zone_report, rep_options) - 8usize];
    ["Offset of field: disk_zone_report::header"]
        [::std::mem::offset_of!(disk_zone_report, header) - 12usize];
    ["Offset of field: disk_zone_report::entries_allocated"]
        [::std::mem::offset_of!(disk_zone_report, entries_allocated) - 88usize];
    ["Offset of field: disk_zone_report::entries_filled"]
        [::std::mem::offset_of!(disk_zone_report, entries_filled) - 92usize];
    ["Offset of field: disk_zone_report::entries_available"]
        [::std::mem::offset_of!(disk_zone_report, entries_available) - 96usize];
    ["Offset of field: disk_zone_report::entries"]
        [::std::mem::offset_of!(disk_zone_report, entries) - 100usize];
};
impl Default for disk_zone_report {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union disk_zone_params {
    pub disk_params: disk_zone_disk_params,
    pub rwp: disk_zone_rwp,
    pub report: disk_zone_report,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of disk_zone_params"][::std::mem::size_of::<disk_zone_params>() - 104usize];
    ["Alignment of disk_zone_params"][::std::mem::align_of::<disk_zone_params>() - 4usize];
    ["Offset of field: disk_zone_params::disk_params"]
        [::std::mem::offset_of!(disk_zone_params, disk_params) - 0usize];
    ["Offset of field: disk_zone_params::rwp"]
        [::std::mem::offset_of!(disk_zone_params, rwp) - 0usize];
    ["Offset of field: disk_zone_params::report"]
        [::std::mem::offset_of!(disk_zone_params, report) - 0usize];
};
impl Default for disk_zone_params {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct disk_zone_args {
    pub zone_cmd: u8,
    pub zone_params: disk_zone_params,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of disk_zone_args"][::std::mem::size_of::<disk_zone_args>() - 108usize];
    ["Alignment of disk_zone_args"][::std::mem::align_of::<disk_zone_args>() - 4usize];
    ["Offset of field: disk_zone_args::zone_cmd"]
        [::std::mem::offset_of!(disk_zone_args, zone_cmd) - 0usize];
    ["Offset of field: disk_zone_args::zone_params"]
        [::std::mem::offset_of!(disk_zone_args, zone_params) - 4usize];
};
impl Default for disk_zone_args {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
